### ISSUE TITLE
cocoapods를 이용해서 인디게이터 뷰를 추가해 주세요.(NVActivityIndicatorView)

### ISSUE THREAD

**Issue by dolfalf** [wnstjd0333/News#14]
데이타로드시 아무표시도 되지않아 상태를 알수 없습니다.
아래 라이브러리를 코코아팟을 이용해서 추가하시고 리퀘스트 보낼때 표시, 리스펀스 받으면 꺼지는
방법으로 구현해 주세요.
https://cocoapods.org/pods/NVActivityIndicatorView

**Comment by wnstjd0333** [comment]
네

**Comment by wnstjd0333** [comment]
네 알겠습니다.
