### ISSUE TITLE
機能テスト書(UT)作成について

### ISSUE THREAD

**Issue by dolfalf** [wnstjd0333/News#15]
첨부한 샘플파일을 복사해서 테스트항목서를 작성해주세요.
과거 상준씨가 연수할 당시 작성한 테스트항목서가 있으니 참고하기 바랍니다.

## 작성시 유의사항

- 가급적 테스트항목당 하나의 결과확인만 기재(하나의 테스트항목에 여러개의 결과확인항목을 넣지말것)
- 테스트순서는 지식이없는사람도 알수있도록 기재
- 정상(正常)인 경우와 이상(異常)인 경우를 망라해서 기입할것

### サンプル機能テスト書
https://docs.google.com/spreadsheets/d/1RFuRmkC8n_6YG4mfjbWRDuPk5Muq6X0TGl3QzgtPLiE/edit?usp=sharing

### 過去サンジュンさんが作成した機能テスト書
https://docs.google.com/spreadsheets/d/1ildYc8_QEQsnFQvXGRGp0zWmObNp5W_Du8ws9F8_zBo/edit?usp=sharing

**Comment by wnstjd0333** [comment]
네 알겠습니다.
