### ISSUE TITLE
브랜치명에 대해서

### ISSUE THREAD

**Issue by dolfalf** [wnstjd0333/News#2]
브랜치명을요 지금 만든거 보니 `feature` 라고 만 했는데 그게 아니고 슬러쉬(`/`)를 넣어줘야해요
예를들어 
유저추가기능을 넣는다고 하면 `feature/add_user`
사진을 넣는 기능에 버그를 고친다면 `bugfix/profile_picture_error`
급하게 수정 이런건.. `hotfix/xxxxx`

이런식으로요.

아래링크 참조하세용.
https://qiita.com/katsunory/items/252c5fd2f70480af9bbb

**Comment by wnstjd0333** [comment]
네 참조하겠습니다
