### ISSUE TITLE
キーワード検索した後に、キーボードが閉じることができない

### ISSUE THREAD

**Issue by dolfalf** [wnstjd0333/News#20]
Everythingメニューでキーワード検索をした後にキーボードが閉じない。

### 再現手順
1. アプリ起動
2. Everythingタブへ移動
3. キーワードを入力し検索

### テスト環境
iOS 13.1、XCode Simulator(iPhoneX Max)

キーワード検索をタップしたらすぐキーボードが閉じる
そして、キーワード検索をキャンセルする時にも同様

**Comment by wnstjd0333** [comment]
해결했습니다.

**Comment by wnstjd0333** [comment]
TopHeadingメニューとEveryThingメニューにイメジが出ないことがある。

**再現手順**

  1. アプリ起動
  2. TopHeadingタブへ移動
  3. スクロールを移動しながらイメジチェック
  4. 国を変わりながらイメジチェック
  5. EveryThingタブへ移動
  6. スクロールを移動しながらイメジチェック
  7. キーワード検索しながらイメジチェック

**テスト環境**

iOS 13.3、IPhone7

記事のイメジが出ない部分があります。

＊イメジのStringにイメジの住所が入っていても出力が出ないです。
（特に韓国、中国の記事）
