### ISSUE TITLE
TopHeadingメニューとEveryThingメニューにイメジが出ないことがある。

### ISSUE THREAD

**Issue by wnstjd0333** [wnstjd0333/News#21]
TopHeadingメニューとEveryThingメニューにイメジが出ないことがある。

**再現手順**

  1. アプリ起動
  2. TopHeadingタブへ移動
  3. スクロールを移動しながらイメジチェック
  4. 国を変わりながらイメジチェック
  5. EveryThingタブへ移動
  6. スクロールを移動しながらイメジチェック
  7. キーワード検索しながらイメジチェック

**テスト環境**

iOS 13.3、IPhone7

記事のイメジが出ない部分があります。

＊イメジのStringにイメジの住所が入っていても出力が出ないです。
（特に韓国、中国の記事）

**Comment by dolfalf** [comment]
PRしました。https://github.com/wnstjd0333/News/pull/33

**Comment by wnstjd0333** [comment]
ありがとうございます！

**Comment by dolfalf** [comment]
어떻게 찾았는지 알려주는 걸 깜빡했는데요.
일단 이미지가 안나온다니 URL을 로그로 출력해서 확인해봤구요.
URL이 있어도 안나오는 이미지가 있어서 디버그 찍어서 확인헤서 원인을 알았어요. 스샷첨부할께요.

<img width="1280" alt="スクリーンショット 2020-03-26 22 25 31" src="https://user-images.githubusercontent.com/4710811/77658048-7ae9d880-6fb9-11ea-9cbf-52c804be1e26.png">

ATS설정변경후 돌려보니 잘 나오더라구요.

<img width="433" alt="スクリーンショット 2020-03-26 22 28 51" src="https://user-images.githubusercontent.com/4710811/77658076-83daaa00-6fb9-11ea-9c70-d33c611bb6a6.png">
