### ISSUE TITLE
アップがBackgroundした後、Foregroundに変わると再起動が必要です。

### ISSUE THREAD

**Issue by wnstjd0333** [wnstjd0333/News#23]
アップがBackgroundした後、Foregroundに変わると再起動が必要です。

### **再現手順**

 1. アプリ起動
 2. ホームボタンを押してアプリをbackgroundにする。
 3. アプリに戻る

### **テスト環境**

iOS 13.3、IPhone7

データの更新がない

**Comment by dolfalf** [comment]
풀리케 했습니다. 확인하시고 참고해서 이슈 해결해 보세요

https://github.com/wnstjd0333/News/pull/32

**Comment by wnstjd0333** [comment]
감사합니다
