### ISSUE TITLE
뉴스앱 레이아웃 구성에 대해서

### ISSUE THREAD

**Issue by dolfalf** [wnstjd0333/News#4]
## 개요
News API 참고하여 레이아웃을 만들어 봤습니다. 아래의 그림과 같이 레이아웃을 만들어 보세요.
레이아웃을 만든후에 기능적인 부분에 대해서 이슈 등록하겠습니다.

## 동작

- 각각 세그먼트를 선택하면 아래 스크롤뷰가 횡으로 이동하면서 해당화면을 보여준다.
- 뷰가 있는 콘텐츠뷰를 스와이프했을경우에도 해당화면으로 이동하며 위에 세크먼트도 같이 갱신된다.

![ニュースレイアウト 001](https://user-images.githubusercontent.com/4710811/74801453-f8b32800-5319-11ea-9fd0-430f926547ed.jpeg)

**Comment by wnstjd0333** [comment]
네 알겠습니다.
