### ISSUE TITLE
뉴스 테이블뷰에 들어갈  셀 레이아웃 구성

### ISSUE THREAD

**Issue by dolfalf** [wnstjd0333/News#9]
테이블 뷰 셀 레이아웃입니다. 
요 레이아웃대로 각각 구성해 주세요.
아마 지금 현재 공통으로 쓰는 방식으로 는 안될테니 각각 만들어야 합니다.

![TableViewCell_layout 001](https://user-images.githubusercontent.com/4710811/75449479-61507380-59b0-11ea-8714-4e037aae7bed.jpeg)

국기 이미지는 요기 링크에서 참조하세요
https://www.flaticon.com/packs/countrys-flags

**Comment by wnstjd0333** [comment]
네 알겠습니다.
